version: '3'

services:
  db:
      platform: linux/x86_64
      image: mysql:8.0
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: masuda
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        TZ: 'Asia/Tokyo'
      volumes:
        - ./mysql:/var/lib/mysql
        - ./sql:/docker-entrypoint-initdb.d
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  app:
    build: ./backend/python
    command: sh -c "cd /code/masuda; python manage.py runserver 0.0.0.0:8107"
    volumes: 
      - ./backend/python/src:/code
    ports:
      - "8107:8107"
    depends_on:
      db:
        condition: service_healthy
